name: TestSelenium
on:
  workflow_dispatch:
jobs:
  TestSelenium:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Install Python dependencies
        run: python -m pip install -r ./.github/script/requirements-esg_cron_job.txt
      - name: Run the test script
        run: python ./.github/script/test_selenium.py
